---
title: |
       | POLI SCI 210
       | Introduction to
       | Empirical Methods in Political Science
       | Spring 2025
format: 
  typst:
    margin:
      x: 1in
      y: 1in
fontsize: 12pt
---

```{=typst} 
#show link: set text(blue)
```

```{=typst}
#block(
  fill: luma(230),
  width: 100%,
  inset: 8pt,
  radius: 4pt,
)[
*Instructor:* Gustavo Diaz (#link("gustavo.diaz@northwestern.edu")) \
*Lecture:* Tues/Thurs 11:00am -- 12:20pm, Harris Hall L07 \
*Canvas:* TBD \
*Student Hours:* Tuesday 2:00 -- 4:00pm, Scott Hall 103

*Teaching Assistants*
- Tanner Bentley (#link("tannerbentley2029@u.northwestern.edu"))
- Chloe Bernadaux (#link("chloebernadaux2028@u.northwestern.edu"))
- Mikhail Turchenko (#link("mturchenko@u.northwestern.edu"))

*TA Student Hours*
#table(
columns: (33%, 33%, 33%),
stroke: none,
align: left,
table.hline(y: 1, start: 0),
[*TA*], [*Time*], [*Office*],
[Bentley], [TBD], [TBD],
[Bernadaux], [TBD], [TBD],
[Turchenko], [TBD], [TBD]
)

*Discussion Sections*
#table(
columns: (13%, 29%, 29%, 29%),
stroke: none,
align: left,
table.hline(y: 1, start: 0),
[*Section*], [*Time*], [*Room*], [*TA*],
[60], [Fr 10:00 -- 10:50AM], [University Hall 312], [TBD],
[61], [Fr 11:00 -- 11:50AM], [University Hall 312], [TBD],
[62], [Fr 1:00 -- 1:50PM], [University Hall 112], [TBD],
[63], [Fr 2:00 -- 2:50PM], [University Hall 412], [TBD],
[64], [Fr 10:00 -- 10:50AM], [University Library 3722], [TBD],
[65], [Fr 11:00 -- 11:50AM], [University Hall 318], [TBD]
)

]


```




{{< pagebreak >}}

# Course Overview


This course introduces the empirical methods used by political scientists to answer research questions, including their appropriate application, advantages, and shortcomings. You will learn how researchers use data in social science contexts, with a particular emphasis on political science topics, across three broad areas: quantitative, experimental, and qualitative studies. This course prepares students to read and evaluate research in subsequent courses on substantive social science topics.

# Learning Objectives

- Identify and explain descriptive and causal inference approaches, as well as their challenges in political science

- Evaluate inferential claims in academic social science research

- Identify types of research designs, explain their strengths and weaknesses, and discuss alternative approaches

- Communicate research processes and findings


# Requirements

There are no requirements to take this course, which fulfills the methodology requirement for Political Science majors. This course also counts toward the Empirical and Deductive Reasoning requirement (formerly known as Formal Studies Distribution Area) at Weinberg College.

# Required Reading

::: {.callout-note}
## **Textbook**

Clipperton, Jean, et al. 2020. [*Empirical Methods in Political Science An Introduction*](https://nulib-oer.github.io/empirical-methods-polisci/). Northwestern University Libraries
:::

This is a _FREE_ resource available through the link above. The rest of the syllabus will refer to the textbook as **EMPS** for short.

Any other required material or reading will be linked in the schedule below and available on Canvas. 


# Grading

This course uses a labor-based grading agreement, commonly known as contract grading. In this course, instead of being given a final grade based on how “good” your submitted assignments are, your final grade will be based on the amount of work you put into the course. The goal is to decouple grades from performance and emphasize learning and effort.

Each assignment is worth a number of points. You need 250 points out of a total of 370 to receive an A. The following table translates points to letter grades. These correspond in ratio to the [Weinberg College grading system](https://weinberg.northwestern.edu/undergraduate/courses-registration-grades/the-grading-system.html).

| **Grade** | **A** | **A-** | **B+** | **B**| **B-** | **C+** | **C** | **C-** | **D** | **F** |
:----|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:----:|:---:|
| Points | $\geq$ 250 | 235 | 215 | 200 | 185 | 165 | 150 | 135 | 100 | $<$ 100 |
| GPA | 4.0 | 3.7 | 3.3 | 3.0 | 2.7 | 2.3 | 2.0 | 1.7 | 1 | 0 |

There are five types of assignments:

1. **Quizzes** (10 points each)
2. **Research design critiques** (10 points each)
3. **AI memos** (10 points each) 
4. **Section participation** (10 points each)
5. **Research proposal (optional)** (30 points)

With the exception of quizzes, which award points based on correct answers, all assignments are marked as satisfactory or unsatisfactory. You receive full points for every assignment marked as satisfactory.

The weekly assignments will be made available no later than the beginning of the first lecture of the corresponding week. These assignments are due on Fridays at 11:59 PM of the week they are assigned. You can choose which assignments to complete, but you will be deducted 20 points if you have not obtained at least 100 points by Friday, May 9. This requirement is waived if you have been approved for accommodations for this course by [AccessibleNU](https://www.northwestern.edu/accessiblenu/).

This course does not formally require attendance, but if every lecture meeting has at least 50% attendance based on the total number of students enrolled in the class at the time of meeting, then every student enrolled in the course will receive **50 extra points** at the end of the term.

As a point of reference, with 8 weeks of available assignments and assuming the collective attendance requirement is met, you should average 25 points every week to secure an A. If you plan complete 3 assignments every week, then you will get an A and have a week to spare.

## Quizzes (10 points each x 8)

Weekly quizzes on the lecture and textbook material will be available on Canvas each week. These quizzes are brief, untimed, and consist only of multiple choice, matching, and true/false questions. Each quiz may be taken as many times as you want before the deadline to earn 10 points. Quizzes may be taken while referencing notes and course materials. The first quiz is due on week 2.

## Research design critiques (10 points each x 8)

Every week has additional non-textbook readings assigned, these are usually published articles that illustrate the application of the methods we discuss that week. You can choose to write a short form document (around 700-1,000 words) that summarizes the question, relevance, and research design of the study in question, and then use course material to evaluate its design or implementation.

Ultimately, your research design critique must answer the question of "what should we change if we were to go back and conduct the study ourselves?" The first research design critique is due on week 3.


## AI memos (10 points each x 8)

Starting on week 2, you can ask a generative AI chatbot to explain the a concept, topic, or issue related to the corresponding week's theme. You should then ask at least five follow up or clarification questions on the topic. You are encouraged to be creative in selecting your prompts, as long as they relate to course material for that week.

Based on your conversation with the AI, you will write a short memo (500-1000 words) summarizing the interaction and evaluating its quality. How does the AI explanation compare to what we discussed in class? Why is it different from the course material? Why is it more/less helpful than what is covered in the textbook or lectures? Do you feel the recommended sources (if any) are credible? At the end of the document, you should also attach a transcript of your conversation with the AI (you can directly ask in the chat to export a copy in Word format, include an external URL, or submit a separate file).

Northwestern University recommends students and faculty to use [Microsoft Copilot](https://www.it.northwestern.edu/about/news-events/2024/microsoft-copilot-available-university-community.html) to engage with generative AI. When using Copilot via Office 365 or Bing while logged into your Northwestern email account, your data will not be shared nor used for product improvement or to train other AI models. However, you are welcome to use your favorite generative AI chatbot as long as you are able to include a transcript in your memo.




## Section participation (10 points each x 8)

During sections, we will engage in additional discussion of the week's material, with emphasis on the assigned non-textbook readings for each week. Your participation will be marked as satisfactory/unsatisfactory in each week. You must actively participate, not merely attend, in order to receive credit.

## Research proposal (30 points)

This course is a good opportunity to start thinking about your own research interests. As an optional assignment, you can write a research grant proposal following the guidelines of the [Office of Undergraduate Research](https://undergradresearch.northwestern.edu) for [academic year](https://undergradresearch.northwestern.edu/funding/ayurg/) or [summer](https://undergradresearch.northwestern.edu/funding/surg/) research grants.

You can only complete this assignment after if you receive prior approval to do so. To receive approval, you must schedule a meeting with a member of the instructional team to discuss your research interests and expectations prior to **Friday, May 16**.

Note that your research proposal needs to be about a political science topic OR connect with one of the methods covered in the course, but not both necessarily.

If approved to complete it, your research proposal is due on **Wednesday, June 11, 11:59 PM**.

# Research Study Participation Requirement

Students enrolled in this course are required to complete a research participation assignment. This will involve taking part in studies conducted by students and faculty from the Department of Political Science, and will include up to 4 hours of research study participation. This will primarily require completing on-line surveys, and in some cases in-person studies at Scott Hall. Students will be able to see how political science studies are conducted and can request information about the studies at the end of the quarter. Students who prefer not to participate in research may opt for an alternative that entails reading a book chapter about political science research and writing a five page reaction paper. The typical chapter is about 20 pages and thus reading it and writing a five-page paper should take approximately four hours. In order to opt for the 5-page paper alternative, please email the lab manager, Jacob Fortier at <jacobfortier2027@u.northwestern.edu>.

# Northwestern University Syllabus Standards

This course follows the [Northwestern University Syllabus Standards](https://www.registrar.northwestern.edu/registration-graduation/northwestern-university-syllabus-standards.html). Students are responsible for familiarizing themselves with this information.


{{< pagebreak >}}

# Schedule

## Week 1 (January 6/8): Introduction and Overview
**NO DISCUSSION SECTIONS**

EMPS Chapters 1-2


## Week 2 (January 13/15): Theory and Data

EMPS Chapters 3-4

<!-- ASSIGN NU FACULTY ONLY -->

<!-- What theory is not: https://doi.org/10.2307/2393788 -->

Krcmaric, Daniel, Stephen C. Nelson, and Andrew Roberts. 2024. ["Billionaire Politicians: A Global Perspective."](https://doi.org/10.1017/S1537592723002761) *Perspectives on Politics* 22 (2): 357-371

## Week 3 (January 20/22): Inference


EMPS Chapter 5

<!-- Rosenzweig, Leah R. and Nicole E. Wilson. 2023. ["State of the Fiscal Contract in Lagos' Informal Settlements."](https://doi.org/10.1007/s12116-022-09369-6) *Studies in Comparative International Development* 58: 1-28 -->

Baum, Matthew A., James N. Druckman, Matthew D. Simonson, Jennifer Lin, and Roy H. Perlis. 2024. ["The Political Consequences of Depression: How Conspiracy Beliefs, Participatory Inclinations, and Depression Affect Support for Political Violence."](https://doi.org/10.1111/ajps.12827) *American Journal of Political Science* 68 (2):575-594


## Week 4 (January 27/29): Surveys

EMPS Chapter 6

<!-- Maybe no need to assign Schwarz, just talk about it? -->
<!-- https://cci.drexel.edu/faculty/sgasson/Readings/Schwarz%20%5B1999%5D%20Self-reports%20-%20How%20the%20questions%20shape%20the%20answers.pdf -->

<!-- https://doi.org/10.1093/ijpor/edz019 -->

<!-- Merseth, Julie Lee. 2018. ["Race-ing solidarity: Asian Americans and support for Black Lives Matter."](https://doi.org/10.1080/21565503.2018.1494015) *Politics, Groups, and Identities* 6 (3): 337-356 -->

Application TBD

## Week 5 (February 3/5): Experiments

EMPS Chapter 7

Naunov, Martin. 2024. ["The Effect of Protesters' Gender on Public Reactions to Protests and Protest Repression."](https://doi.org/10.1017/S0003055424000133) *American Political Science Review*

<!-- https://doi.org/10.1086/693984 -->

<!-- https://doi.org/10.1017/S0003055413000488 -->


## Week 6 (February 10/12): Large N

EMPS Chapter 8

Harbridge-Yong, Laurel,  Craig Volden, and Alan E. Wiseman. 2023. ["The Bipartisan Path to Effective Lawmaking."](https://doi.org/10.1086/723805) *Journal of Politics* 85 (3): 795-1165


## Week 7 (February 17/19): Quasi-Experiments

Huntinton-Klein, Nick. 2022. [*The Effect: An Introduction to Research Design and Causality*](https://theeffectbook.net). Chapman & Hall. Chapter 18

Cattaneo, Matias D., Nicolás Idrobo, and Rocío Titiunik. 2020. [*A Practical Introduction to Regression Discontinuity Designs: Foundations*](https://doi.org/10.1017/9781108684606). Cambridge University Press. Chapters 1-4

García-Montoya, Laura, Ana Arjona, and Matthew Lacombe. 2022. ["Violence and Voting in the United States: How School Shootings Affect Elections."](https://doi.org/10.1017/S0003055421001179) *American Political Science Review* 116 (3): 807-826
<!-- Critique: https://doi.org/10.1017/S0003055424000108 -->


<!-- Saab: https://doi.org/10.1016/j.electstud.2025.103010 -->


## Week 8 (February 24/26): Small N

EMPS Chapter 9

<!-- Candidates -->
<!-- Iza Ding ethnography: https://doi.org/10.1017/s0043887120000131 -->

<!-- Dani Gilbert interviews: https://doi.org/10.1017/S0003055422000041 -->
Gilbert, Danielle. 2022. ["The Logic of Kidnapping in Civil War: Evidence from Colombia."](https://doi.org/10.1017/S0003055422000041) *American Political Science Review* 116 (4): 1226-1241

## Week 9 (March 3/5): Machine Learning

EMPS Chapter 12

<!-- Ligbober string matching: https://doi.org/10.1017/psrm.2024.55 -->

Libgober, Brian and Connor T. Jerzak. 2024. ["Linking datasets on organizations using half a billion open-collaborated records."](https://doi.org/10.1017/psrm.2024.55) *Political Science Research and Methods* 

## Week 10 (March 10/12): Weinberg College Reading Period

**NO CLASS**








